const APP_VERSION='1.0.0';
window.KEYWORD_SPEAKING_VERSION=APP_VERSION;
const $=id=>document.getElementById(id);
const PAPERS=[...(window.ADAPTIVE_EXAM_CAMBRIDGE_PAPERS||[]),...(window.ADAPTIVE_EXAM_PAPERS||[])];
const QUESTIONS=PAPERS.flatMap(p=>(p.parts?.[4]?.items||[]).map((it,i)=>({...it,_paper:p.label||p.id,_paperId:p.id,_exam:Number(p.examNumber)||null,_qid:(p.id||p.label)+':'+(it.n??i)}))).filter(q=>q.first&&q.keyword&&q.secondBefore!==undefined&&q.secondAfter!==undefined&&(q.answers?.length||q.answer));
const SESSION_SIZE=15,STATS_KEY='keywordSpeakingStatsV1',APP_ID='keyword-speaking';
let secondsPerQuestion=180,session=null,index=0,timerId=null,deadline=0,recognition=null,listening=false,answered=false,lastVoiceTranscript='',composing=false,gboardIdleTimer=null;
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function norm(v){return String(v||'').toLowerCase().replace(/[’‘]/g,"'").replace(/[.,!?;:]/g,' ').replace(/\s+/g,' ').trim();}
function canon(v){let s=norm(v);const map=[["won't","will not"],["can't","cannot"],["shan't","shall not"],["don't","do not"],["doesn't","does not"],["didn't","did not"],["isn't","is not"],["aren't","are not"],["wasn't","was not"],["weren't","were not"],["haven't","have not"],["hasn't","has not"],["hadn't","had not"],["wouldn't","would not"],["shouldn't","should not"],["couldn't","could not"],["mustn't","must not"],["i'm","i am"],["you're","you are"],["we're","we are"],["they're","they are"],["he's","he is"],["she's","she is"],["it's","it is"]];for(const [a,b] of map)s=s.split(a).join(b);return s.replace(/\s+/g,' ').trim();}
function speechCanon(v){let s=canon(v);const map=[["i'd","i would"],["you'd","you would"],["we'd","we would"],["they'd","they would"],["he'd","he would"],["she'd","she would"],["i'll","i will"],["you'll","you will"],["we'll","we will"],["they'll","they will"],["he'll","he will"],["she'll","she will"]];for(const [a,b] of map)s=s.split(a).join(b);return s;}
function expectedVariants(q){const raw=[...(q.answers||[]),q.answer,q.display].filter(Boolean);const out=[];for(const item of raw){for(const alt of String(item).split(/\s+\/\s+/)){const optional=alt.match(/\(([^)]+)\)/);if(optional){out.push(alt.replace(/\([^)]*\)/g,'').replace(/\s+/g,' ').trim());out.push(alt.replace(/[()]/g,'').replace(/\s+/g,' ').trim());}else out.push(alt.trim());}}return [...new Set(out.filter(Boolean))];}
function wordCountCambridge(v){return speechCanon(v).split(' ').filter(Boolean).length;}
function containsKeyword(v,q){const u=speechCanon(v).split(' '),k=speechCanon(q.keyword||'').split(' ');return k.every(w=>u.includes(w));}
function longestCommonRun(a,b){const A=speechCanon(a).split(' ').filter(Boolean),B=speechCanon(b).split(' ').filter(Boolean);let best=0;for(let i=0;i<A.length;i++)for(let j=0;j<B.length;j++){let n=0;while(i+n<A.length&&j+n<B.length&&A[i+n]===B[j+n])n++;if(n>best)best=n;}return best;}
function scoreTransformation(user,q){const raw=String(user||'').trim(),variants=expectedVariants(q);if(!raw)return{points:0,max:2,exact:false,variant:variants[0]||'',reason:'empty'};const wc=wordCountCambridge(raw);for(const v of variants)if(canon(raw)===canon(v))return{points:2,max:2,exact:true,variant:v,reason:'exact'};if(wc<2||wc>5||!containsKeyword(raw,q))return{points:0,max:2,exact:false,variant:variants[0]||'',reason:wc<2||wc>5?'word-count':'keyword'};let best={run:0,variant:variants[0]||''};for(const v of variants){const run=longestCommonRun(raw,v),need=Math.max(2,Math.ceil(wordCountCambridge(v)/2));if(run>best.run)best={run,variant:v,need};if(run>=need)return{points:1,max:2,exact:false,variant:v,reason:'partial'};}return{points:0,max:2,exact:false,variant:best.variant,reason:'mismatch'};}
function commitGboardInput(){if(answered||listening||composing)return;const input=$('answer'),raw=input.value.trim();if(!raw)return;const p=parseFullSentence(raw);if(p.preScore>=.58)flashFixed('secondBefore');if(p.sufScore>=.58)flashFixed('secondAfter');if(p.full){input.value=p.gap;input.dataset.extracted='1';$('micStatus').textContent=`Frase completa detectada · he quitado lo repetido y dejo: “${p.gap}”`;try{input.setSelectionRange(input.value.length,input.value.length)}catch{}}}

function wordDistance(a,b){const A=a||[],B=b||[],m=A.length,n=B.length,d=Array.from({length:m+1},()=>Array(n+1).fill(0));for(let i=0;i<=m;i++)d[i][0]=i;for(let j=0;j<=n;j++)d[0][j]=j;for(let i=1;i<=m;i++)for(let j=1;j<=n;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(A[i-1]===B[j-1]?0:1));return d[m][n];}
function tokenSimilarity(a,b){const A=a||[],B=b||[];if(!A.length&&!B.length)return 1;if(!A.length||!B.length)return 0;const dist=wordDistance(A,B);return Math.max(0,1-dist/Math.max(A.length,B.length,1));}
function extractGapCandidate(text,q=current()){if(!q||!text)return{full:false,gap:'',preScore:0,sufScore:0,score:0};const t=speechCanon(text).split(' ').filter(Boolean),before=speechCanon(q.secondBefore||'').split(' ').filter(Boolean),after=speechCanon(q.secondAfter||'').split(' ').filter(Boolean),kw=speechCanon(q.keyword||'').split(' ').filter(Boolean);if(!t.length)return{full:false,gap:'',preScore:0,sufScore:0,score:0};let best=null;for(let len=2;len<=5;len++){for(let i=0;i+len<=t.length;i++){const gap=t.slice(i,i+len);if(kw.length&&!kw.every(w=>gap.includes(w)))continue;const left=t.slice(0,i),right=t.slice(i+len),pre=before.length?tokenSimilarity(left,before):1,suf=after.length?tokenSimilarity(right,after):1;const active=(before.length?1:0)+(after.length?1:0),score=active===2?(pre+suf)/2:before.length?pre:after.length?suf:0;if(!best||score>best.score)best={gap:gap.join(' '),preScore:pre,sufScore:suf,score,leftCount:left.length,rightCount:right.length};}}
if(!best)return{full:false,gap:'',preScore:0,sufScore:0,score:0};const preOk=!before.length||best.preScore>=.45,sufOk=!after.length||best.sufScore>=.45,scoreOk=best.score>=.58;return{...best,full:preOk&&sufOk&&scoreOk};}
function parseFullSentence(text,q=current()){return extractGapCandidate(text,q);}
function flashFixed(id){const el=$(id);if(!el)return;el.classList.remove('heard');void el.offsetWidth;el.classList.add('heard');clearTimeout(el._heardTimer);el._heardTimer=setTimeout(()=>el.classList.remove('heard'),760);}
function showRecognitionProgress(text,commit=false){const p=parseFullSentence(text);if(p.preScore>=.58)flashFixed('secondBefore');if(p.sufScore>=.58)flashFixed('secondAfter');if(p.full){if(commit||listening){$('answer').value=p.gap;$('answer').dataset.extracted='1';}$('micStatus').textContent=`Frase completa reconocida · hueco: “${p.gap}”`;return p;}if(commit){$('answer').value=text.trim();$('answer').dataset.extracted='0';}return p;}
function show(id){['startScreen','gameScreen','resultScreen','statsScreen','micScreen'].forEach(x=>$(x).classList.toggle('hidden',x!==id));window.scrollTo(0,0);}
function load(){try{return JSON.parse(localStorage.getItem(STATS_KEY))||{sessions:[],items:{}}}catch{return{sessions:[],items:{}}}}
function save(x){localStorage.setItem(STATS_KEY,JSON.stringify(x));}
function medalCounts(){return window.AdrianAchievements?.countsFromHistory?.(load().sessions)||{blue:0,violet:0,gold:0};}
function aggregate(){const d=load(),s=d.sessions||[],correct=s.reduce((n,x)=>n+(x.correct||0),0),total=s.reduce((n,x)=>n+(x.total||0),0),voice=s.reduce((n,x)=>n+(x.voiceAnswers||0),0),answers=s.reduce((n,x)=>n+(x.questionCount||x.total||0),0);return{sessions:s.length,correct,total,accuracy:total?Math.round(correct/total*100):0,voiceRate:answers?Math.round(voice/answers*100):0};}
function renderHome(){const a=aggregate();$('homeStats').innerHTML=stat(a.sessions,'SESIONES')+stat(a.total?a.accuracy+'%':'—','ACIERTO')+stat(QUESTIONS.length,'PREGUNTAS');$('homeMedals').innerHTML=window.AdrianAchievements?.medalStripHtml?.(medalCounts(),{context:'summary',compact:true})||'';$('speechSupport').textContent=SpeechRecognition?'Micrófono disponible en este navegador.':'Este navegador no ofrece reconocimiento de voz; el teclado seguirá funcionando.';$('speechSupport').classList.toggle('bad',!SpeechRecognition);}
function stat(v,l){return `<div class="stat"><b>${esc(v)}</b><span>${esc(l)}</span></div>`}
function itemHistory(q){return load().items?.[q._qid]||{attempts:0,correct:0,points:0}}
function pickQuestions(){const ranked=QUESTIONS.map(q=>{const h=itemHistory(q),earned=Number.isFinite(h.points)?h.points:(h.correct||0)*2,acc=h.attempts?earned/(h.attempts*2):.45,weight=1.2+(1-acc)*2+1/Math.sqrt(h.attempts+1);return{q,key:Math.random()**(1/weight)}}).sort((a,b)=>b.key-a.key);return ranked.slice(0,Math.min(SESSION_SIZE,ranked.length)).map(x=>x.q)}
function startSession(){stopRecognition();clearTimer();session={startedAt:Date.now(),questions:pickQuestions(),results:[],correct:0,voiceAnswers:0};index=0;show('gameScreen');renderQuestion();}
function current(){return session?.questions?.[index]||null}
function renderQuestion(){clearTimer();stopRecognition();answered=false;const q=current();if(!q)return finishSession();$('progressMain').textContent=`${index+1} / ${session.questions.length}`;$('paperLabel').textContent=q._exam?`EXAM ${String(q._exam).padStart(2,'0')}`:String(q._paper||'PART 4').toUpperCase();$('scoreTop').textContent=`${session.correct}/${session.questions.length*2}`;$('questionNo').textContent=`QUESTION ${q.n??index+1}`;$('first').textContent=q.first||'';$('keyword').textContent=q.keyword||'';$('secondBefore').textContent=q.secondBefore||'';$('secondAfter').textContent=q.secondAfter||'';$('answer').value='';$('answer').dataset.extracted='0';lastVoiceTranscript='';$('answer').disabled=false;$('micBtn').disabled=false;$('checkBtn').disabled=false;$('retryBtn').disabled=false;$('feedback').className='feedback hidden';$('feedback').innerHTML='';$('nextBtn').classList.add('hidden');$('micStatus').textContent=SpeechRecognition?'Di la frase completa o solo el hueco. También puedes dictar con Gboard.':'Escribe el hueco o la frase completa.';startTimer();}
function startTimer(){if(secondsPerQuestion===0){$("timerText").textContent="∞";$("timer").style.setProperty("--p",100);$("timer").classList.remove("low");return}deadline=Date.now()+secondsPerQuestion*1000;tick();timerId=setInterval(tick,200)}
function tick(){const left=Math.max(0,Math.ceil((deadline-Date.now())/1000)),p=Math.max(0,Math.min(100,(deadline-Date.now())/(secondsPerQuestion*10)));$('timerText').textContent=left;$('timer').style.setProperty('--p',p);$('timer').classList.toggle('low',left<=15);if(left<=0&&!answered){clearTimer();submitAnswer(true)}}
function clearTimer(){if(timerId){clearInterval(timerId);timerId=null}}
function configureRecognition(target,statusEl,onDone){if(!SpeechRecognition)return null;const r=new SpeechRecognition();r.lang='en-GB';r.continuous=false;r.interimResults=true;r.maxAlternatives=5;r.onstart=()=>{listening=true;statusEl?.classList.add('listening');if(statusEl)statusEl.textContent='Escuchando…';$('micBtn')?.classList.add('listening')};r.onresult=e=>{let text='';for(let i=0;i<e.results.length;i++)text+=e.results[i][0].transcript+' ';text=text.trim();lastVoiceTranscript=text;if(target.id==='answer'){const p=showRecognitionProgress(text,false);if(!p.full)target.value=text;}else target.value=text;};r.onerror=e=>{if(statusEl){statusEl.textContent=e.error==='not-allowed'?'Permiso de micrófono bloqueado. Puedes usar el teclado.':'No he podido reconocerlo. Repite o usa el teclado.';statusEl.classList.remove('listening')}};r.onend=()=>{listening=false;$('micBtn')?.classList.remove('listening');statusEl?.classList.remove('listening');if(target.id==='answer'&&lastVoiceTranscript){const p=showRecognitionProgress(lastVoiceTranscript,true);if(!p.full&&statusEl)statusEl.textContent=`He entendido: “${target.value.trim()}”. Puedes decir el hueco o la frase completa.`;}else if(statusEl&&target.value.trim())statusEl.textContent=`He entendido: “${target.value.trim()}”.`;onDone?.(target.value.trim())};return r}
function startMic(){if(answered)return;if(!SpeechRecognition){$('answer').focus();return}if(listening){stopRecognition();return}recognition=configureRecognition($('answer'),$('micStatus'),()=>{});try{recognition.start()}catch{}}
function stopRecognition(){if(recognition){try{recognition.stop()}catch{}recognition=null}listening=false;$('micBtn')?.classList.remove('listening')}
function submitAnswer(timeout=false){if(answered)return;const q=current();let raw=$('answer').value.trim();const parsed=parseFullSentence(raw,q);if(parsed.full){raw=parsed.gap;$('answer').value=raw;$('answer').dataset.extracted='1';flashFixed('secondBefore');flashFixed('secondAfter');}if(!timeout&&!raw){$('micStatus').textContent='Di la respuesta o escríbela antes de comprobar.';$('answer').focus();return}answered=true;clearTimer();stopRecognition();const score=timeout?{points:0,max:2,exact:false,variant:expectedVariants(q)[0]||'',reason:'timeout'}:scoreTransformation(raw,q);session.correct+=score.points;const usedVoice=$('answer').dataset.voice==='1';if(usedVoice)session.voiceAnswers++;const result={qid:q._qid,n:q.n,first:q.first,keyword:q.keyword,user:raw,expected:score.variant||expectedVariants(q)[0]||'',points:score.points,maxPoints:2,correct:score.points===2,timeout,skill:q.skill||'',explanation:q.explanation||'',usedVoice};session.results.push(result);$('answer').disabled=true;$('micBtn').disabled=true;$('checkBtn').disabled=true;$('retryBtn').disabled=true;$('scoreTop').textContent=`${session.correct}/${session.questions.length*2}`;const f=$('feedback');f.className=`feedback ${score.points===2?'ok':score.points===1?'partial':'bad'}`;if(score.points===2)f.innerHTML=`<b>2/2 · Correcto.</b><span class="expected">${esc(result.expected)}</span><small>${esc(result.skill)}</small>`;else if(score.points===1)f.innerHTML=`<b>1/2 · Parcial estimado.</b><span>Una parte importante coincide con la estructura correcta.</span><small>Solución completa: <span class="expected">${esc(result.expected)}</span></small>`;else f.innerHTML=`<b>${timeout?'Tiempo.':'0/2 · Revisa la transformación.'}</b><span>Respuesta: <span class="expected">${esc(result.expected)}</span></span>${raw?`<small>Has dicho/escrito: ${esc(raw)}</small>`:''}<small>${esc(result.explanation)}</small>`;$('nextBtn').textContent=index===session.questions.length-1?'VER RESULTADO':'SIGUIENTE';$('nextBtn').classList.remove('hidden');}
function next(){if(!answered)return;index++;if(index>=session.questions.length)finishSession();else renderQuestion()}
function finishSession(){clearTimer();stopRecognition();if(!session)return;const data=load(),durationSec=Math.round((Date.now()-session.startedAt)/1000),sessionId='kw-'+(crypto.randomUUID?.()||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2));for(const r of session.results){const h=data.items[r.qid]||{attempts:0,correct:0,points:0};h.attempts++;h.points=(h.points||0)+(r.points||0);if(r.points===2)h.correct=(h.correct||0)+1;data.items[r.qid]=h}const savedSession={id:sessionId,eventId:sessionId,completedAt:new Date().toISOString(),correct:session.correct,total:session.questions.length*2,questionCount:session.questions.length,voiceAnswers:session.voiceAnswers,durationSec,secondsPerQuestion,results:session.results.slice(-SESSION_SIZE)};data.sessions.push(savedSession);save(data);const counts=medalCounts();$('resultScore').textContent=`${session.correct}/${session.questions.length*2}`;$('resultSub').textContent=`${Math.round(session.correct/(session.questions.length*2)*100)}% · ${session.voiceAnswers} respuestas por voz · ${secondsPerQuestion===0?'sin límite':('límite '+secondsPerQuestion+'s')}`;$('achievement').innerHTML=window.AdrianAchievements?.badgeHtml?.(session.correct,session.questions.length*2)||'';$('resultMedals').innerHTML=window.AdrianAchievements?.medalStripHtml?.(counts,{context:'summary',compact:true})||'';const misses=session.results.filter(x=>(x.points||0)<2);$('review').innerHTML=misses.map(x=>`<div class="review-row ${x.points===1?'partial':'bad'}"><b>${x.points||0}/2 · ${esc(x.keyword)}</b><small><strong>Tu respuesta:</strong> ${esc(x.user||'—')}</small><small><strong>Solución:</strong> ${esc(x.expected)}</small><small>${esc(x.first)}</small>${x.explanation?`<small>${esc(x.explanation)}</small>`:''}</div>`).join('')||'<div class="review-row"><b>Sesión limpia.</b><small>30/30 · todas las transformaciones correctas.</small></div>';window.AdrianAchievements?.play?.(null,session.correct,session.questions.length*2);show('resultScreen');renderHome();Promise.resolve(window.AdrianOca?.resolve?.({eventId:'keyword:'+sessionId,appId:APP_ID,correct:session.correct,total:session.questions.length*2})).catch(()=>{});}
function renderStats(){const a=aggregate(),d=load(),counts=medalCounts(),recent=(d.sessions||[]).slice(-8);$('statsSummary').innerHTML=`<div class="stats-card"><b>${a.sessions}</b><span>sesiones completas</span></div><div class="stats-card"><b>${a.accuracy}%</b><span>${a.correct}/${a.total} puntos acumulados</span></div><div class="stats-card"><b>${a.voiceRate}%</b><span>respuestas registradas por voz</span></div><div class="stats-card"><b>${recent.length?Math.round(recent.reduce((n,x)=>n+x.correct/x.total*100,0)/recent.length):0}%</b><span>media de las últimas ${recent.length} sesiones</span></div>`;$('statsMedals').innerHTML=window.AdrianAchievements?.medalStripHtml?.(counts,{context:'summary',compact:false})||'';show('statsScreen')}
function micTest(){if(!SpeechRecognition){$('micTestResult').textContent='Este navegador no ofrece reconocimiento de voz.';return}const box=$('micTestResult'),target={value:''};const r=configureRecognition(target,box,v=>{box.textContent=v?`He entendido: “${v}”`:'No he recibido ninguna frase.'});recognition=r;try{r.start()}catch{}}
function clearAnswer(){$('answer').value='';$('answer').dataset.voice='0';$('micStatus').textContent='Respuesta borrada. Puedes hablar otra vez o escribir.';$('answer').focus()}
$('micBtn').onclick=()=>{if(!answered){$('answer').dataset.voice='1';startMic()}};$('checkBtn').onclick=()=>submitAnswer(false);$('retryBtn').onclick=clearAnswer;$('nextBtn').onclick=next;$('startBtn').onclick=startSession;$('againBtn').onclick=startSession;$('statsBtn').onclick=renderStats;$('statsHomeBtn').onclick=()=>{renderHome();show('startScreen')};$('resultHomeBtn').onclick=()=>{renderHome();show('startScreen')};$('quitBtn').onclick=()=>{clearTimer();stopRecognition();renderHome();show('startScreen')};$('practiceBtn').onclick=()=>show('micScreen');$('micHomeBtn').onclick=()=>{stopRecognition();show('startScreen')};$('micTestBtn').onclick=micTest;function setTime(sec,source=null){secondsPerQuestion=Math.max(0,Number(sec)||0);document.querySelectorAll('.time-choice').forEach(x=>x.classList.toggle('active',x===source));if(source&&$('customTime'))$('customTime').value=''}document.querySelectorAll('.time-choice').forEach(b=>b.onclick=()=>setTime(Number(b.dataset.sec),b));$('customTimeBtn').onclick=()=>{const v=Math.max(15,Math.round(Number($('customTime').value)||180));$('customTime').value=v;setTime(v,null)};$('customTime').addEventListener('keydown',e=>{if(e.key==='Enter')$('customTimeBtn').click()});
$('answer').addEventListener('compositionstart',()=>{composing=true;clearTimeout(gboardIdleTimer)});$('answer').addEventListener('compositionupdate',()=>{clearTimeout(gboardIdleTimer)});$('answer').addEventListener('compositionend',()=>{composing=false;commitGboardInput()});$('answer').addEventListener('input',e=>{if(!listening&&document.activeElement===$('answer')){$('answer').dataset.voice='0';$('answer').dataset.extracted='0'}});$('answer').addEventListener('blur',()=>{clearTimeout(gboardIdleTimer);commitGboardInput()});$('answer').addEventListener('keydown',e=>{if(e.key==='Enter'&&!answered){clearTimeout(gboardIdleTimer);commitGboardInput();submitAnswer(false)}});
renderHome();show('startScreen');
