const $=id=>document.getElementById(id);
const PAPERS=[...(window.ADAPTIVE_EXAM_CAMBRIDGE_PAPERS||[]),...(window.ADAPTIVE_EXAM_PAPERS||[])];
const QUESTIONS=PAPERS.flatMap(p=>(p.parts?.[4]?.items||[]).map((it,i)=>({...it,_paper:p.label||p.id,_paperId:p.id,_exam:Number(p.examNumber)||null,_qid:(p.id||p.label)+':'+(it.n??i)}))).filter(q=>q.first&&q.keyword&&q.secondBefore!==undefined&&q.secondAfter!==undefined&&(q.answers?.length||q.answer));
const SESSION_SIZE=15,STATS_KEY='keywordSpeakingStatsV1';
let secondsPerQuestion=180,session=null,index=0,timerId=null,deadline=0,recognition=null,listening=false,answered=false,inputDebounce=null,lastVoiceTranscript='';
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function norm(v){return String(v||'').toLowerCase().replace(/[’‘]/g,"'").replace(/[.,!?;:]/g,' ').replace(/\s+/g,' ').trim();}
function canon(v){let s=norm(v);const map=[["won't","will not"],["can't","cannot"],["shan't","shall not"],["don't","do not"],["doesn't","does not"],["didn't","did not"],["isn't","is not"],["aren't","are not"],["wasn't","was not"],["weren't","were not"],["haven't","have not"],["hasn't","has not"],["hadn't","had not"],["wouldn't","would not"],["shouldn't","should not"],["couldn't","could not"],["mustn't","must not"],["i'm","i am"],["you're","you are"],["we're","we are"],["they're","they are"],["he's","he is"],["she's","she is"],["it's","it is"]];for(const [a,b] of map)s=s.split(a).join(b);return s.replace(/\s+/g,' ').trim();}
function speechCanon(v){let s=canon(v);const map=[["i'd","i would"],["you'd","you would"],["we'd","we would"],["they'd","they would"],["he'd","he would"],["she'd","she would"],["i'll","i will"],["you'll","you will"],["we'll","we will"],["they'll","they will"],["he'll","he will"],["she'll","she will"]];for(const [a,b] of map)s=s.split(a).join(b);return s;}
function wordDistance(a,b){const A=a||[],B=b||[],m=A.length,n=B.length,d=Array.from({length:m+1},()=>Array(n+1).fill(0));for(let i=0;i<=m;i++)d[i][0]=i;for(let j=0;j<=n;j++)d[0][j]=j;for(let i=1;i<=m;i++)for(let j=1;j<=n;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(A[i-1]===B[j-1]?0:1));return d[m][n];}
function bestEdgeMatch(transcriptWords,fixedWords,side){if(!fixedWords.length)return{score:1,consumed:0};let best={score:0,consumed:0};const min=Math.max(1,fixedWords.length-3),max=Math.min(transcriptWords.length,fixedWords.length+3);for(let len=min;len<=max;len++){const slice=side==='start'?transcriptWords.slice(0,len):transcriptWords.slice(transcriptWords.length-len);const dist=wordDistance(slice,fixedWords),score=1-dist/Math.max(slice.length,fixedWords.length,1);if(score>best.score)best={score,consumed:len}}return best;}
function parseFullSentence(text,q=current()){if(!q||!text)return{full:false,gap:'',preScore:0,sufScore:0};const t=speechCanon(text).split(' ').filter(Boolean),before=speechCanon(q.secondBefore||'').split(' ').filter(Boolean),after=speechCanon(q.secondAfter||'').split(' ').filter(Boolean);if(!t.length)return{full:false,gap:'',preScore:0,sufScore:0};const pre=bestEdgeMatch(t,before,'start'),suf=bestEdgeMatch(t,after,'end'),room=t.length-pre.consumed-suf.consumed,full=pre.score>=.72&&suf.score>=.72&&room>0;return{full,gap:full?t.slice(pre.consumed,t.length-suf.consumed).join(' '):'',preScore:pre.score,sufScore:suf.score};}
function flashFixed(id){const el=$(id);if(!el)return;el.classList.remove('heard');void el.offsetWidth;el.classList.add('heard');clearTimeout(el._heardTimer);el._heardTimer=setTimeout(()=>el.classList.remove('heard'),760);}
function showRecognitionProgress(text,commit=false){const p=parseFullSentence(text);if(p.preScore>=.58)flashFixed('secondBefore');if(p.sufScore>=.58)flashFixed('secondAfter');if(p.full){if(commit||listening){$('answer').value=p.gap;$('answer').dataset.extracted='1';}$('micStatus').textContent=`Frase completa reconocida · hueco: “${p.gap}”`;return p;}if(commit){$('answer').value=text.trim();$('answer').dataset.extracted='0';}return p;}
function extractFullSentenceFromInput(){if(answered||listening)return;const raw=$('answer').value.trim();if(!raw)return;const p=parseFullSentence(raw);if(p.preScore>=.58)flashFixed('secondBefore');if(p.sufScore>=.58)flashFixed('secondAfter');if(p.full){$('answer').value=p.gap;$('answer').dataset.extracted='1';$('micStatus').textContent=`Frase completa detectada · he dejado solo el hueco: “${p.gap}”`;}}
function show(id){['startScreen','gameScreen','resultScreen','statsScreen','micScreen'].forEach(x=>$(x).classList.toggle('hidden',x!==id));window.scrollTo(0,0);}
function load(){try{return JSON.parse(localStorage.getItem(STATS_KEY))||{sessions:[],items:{}}}catch{return{sessions:[],items:{}}}}
function save(x){localStorage.setItem(STATS_KEY,JSON.stringify(x));}
function medalCounts(){return window.AdrianAchievements?.countsFromHistory?.(load().sessions)||{blue:0,violet:0,gold:0};}
function aggregate(){const d=load(),s=d.sessions||[],correct=s.reduce((n,x)=>n+(x.correct||0),0),total=s.reduce((n,x)=>n+(x.total||0),0),voice=s.reduce((n,x)=>n+(x.voiceAnswers||0),0),answers=s.reduce((n,x)=>n+(x.total||0),0);return{sessions:s.length,correct,total,accuracy:total?Math.round(correct/total*100):0,voiceRate:answers?Math.round(voice/answers*100):0};}
function renderHome(){const a=aggregate();$('homeStats').innerHTML=stat(a.sessions,'SESIONES')+stat(a.total?a.accuracy+'%':'—','ACIERTO')+stat(QUESTIONS.length,'PREGUNTAS');$('homeMedals').innerHTML=window.AdrianAchievements?.medalStripHtml?.(medalCounts(),{context:'summary',compact:true})||'';$('speechSupport').textContent=SpeechRecognition?'Micrófono disponible en este navegador.':'Este navegador no ofrece reconocimiento de voz; el teclado seguirá funcionando.';$('speechSupport').classList.toggle('bad',!SpeechRecognition);}
function stat(v,l){return `<div class="stat"><b>${esc(v)}</b><span>${esc(l)}</span></div>`}
function itemHistory(q){return load().items?.[q._qid]||{attempts:0,correct:0}}
function pickQuestions(){const ranked=QUESTIONS.map(q=>{const h=itemHistory(q),acc=h.attempts?h.correct/h.attempts:.45,weight=1.2+(1-acc)*2+1/Math.sqrt(h.attempts+1);return{q,key:Math.random()**(1/weight)}}).sort((a,b)=>b.key-a.key);return ranked.slice(0,Math.min(SESSION_SIZE,ranked.length)).map(x=>x.q)}
function startSession(){stopRecognition();clearTimer();session={startedAt:Date.now(),questions:pickQuestions(),results:[],correct:0,voiceAnswers:0};index=0;show('gameScreen');renderQuestion();}
function current(){return session?.questions?.[index]||null}
function renderQuestion(){clearTimer();stopRecognition();answered=false;const q=current();if(!q)return finishSession();$('progressMain').textContent=`${index+1} / ${session.questions.length}`;$('paperLabel').textContent=q._exam?`EXAM ${String(q._exam).padStart(2,'0')}`:String(q._paper||'PART 4').toUpperCase();$('scoreTop').textContent=`${session.correct} ✓`;$('questionNo').textContent=`QUESTION ${q.n??index+1}`;$('first').textContent=q.first||'';$('keyword').textContent=q.keyword||'';$('secondBefore').textContent=q.secondBefore||'';$('secondAfter').textContent=q.secondAfter||'';$('answer').value='';$('answer').dataset.extracted='0';lastVoiceTranscript='';$('answer').disabled=false;$('micBtn').disabled=false;$('checkBtn').disabled=false;$('retryBtn').disabled=false;$('feedback').className='feedback hidden';$('feedback').innerHTML='';$('nextBtn').classList.add('hidden');$('micStatus').textContent=SpeechRecognition?'Di la frase completa o solo el hueco. También puedes dictar con Gboard.':'Escribe el hueco o la frase completa.';startTimer();}
function startTimer(){if(secondsPerQuestion===0){$("timerText").textContent="∞";$("timer").style.setProperty("--p",100);$("timer").classList.remove("low");return}deadline=Date.now()+secondsPerQuestion*1000;tick();timerId=setInterval(tick,200)}
function tick(){const left=Math.max(0,Math.ceil((deadline-Date.now())/1000)),p=Math.max(0,Math.min(100,(deadline-Date.now())/(secondsPerQuestion*10)));$('timerText').textContent=left;$('timer').style.setProperty('--p',p);$('timer').classList.toggle('low',left<=15);if(left<=0&&!answered){clearTimer();submitAnswer(true)}}
function clearTimer(){if(timerId){clearInterval(timerId);timerId=null}}
function configureRecognition(target,statusEl,onDone){if(!SpeechRecognition)return null;const r=new SpeechRecognition();r.lang='en-GB';r.continuous=false;r.interimResults=true;r.maxAlternatives=5;r.onstart=()=>{listening=true;statusEl?.classList.add('listening');if(statusEl)statusEl.textContent='Escuchando…';$('micBtn')?.classList.add('listening')};r.onresult=e=>{let text='';for(let i=0;i<e.results.length;i++)text+=e.results[i][0].transcript+' ';text=text.trim();lastVoiceTranscript=text;if(target.id==='answer'){const p=showRecognitionProgress(text,false);if(!p.full)target.value=text;}else target.value=text;};r.onerror=e=>{if(statusEl){statusEl.textContent=e.error==='not-allowed'?'Permiso de micrófono bloqueado. Puedes usar el teclado.':'No he podido reconocerlo. Repite o usa el teclado.';statusEl.classList.remove('listening')}};r.onend=()=>{listening=false;$('micBtn')?.classList.remove('listening');statusEl?.classList.remove('listening');if(target.id==='answer'&&lastVoiceTranscript){const p=showRecognitionProgress(lastVoiceTranscript,true);if(!p.full&&statusEl)statusEl.textContent=`He entendido: “${target.value.trim()}”. Puedes decir el hueco o la frase completa.`;}else if(statusEl&&target.value.trim())statusEl.textContent=`He entendido: “${target.value.trim()}”.`;onDone?.(target.value.trim())};return r}
function startMic(){if(answered)return;if(!SpeechRecognition){$('answer').focus();return}if(listening){stopRecognition();return}recognition=configureRecognition($('answer'),$('micStatus'),()=>{});try{recognition.start()}catch{}}
function stopRecognition(){if(recognition){try{recognition.stop()}catch{}recognition=null}listening=false;$('micBtn')?.classList.remove('listening')}
function submitAnswer(timeout=false){if(answered)return;const q=current();let raw=$('answer').value.trim();const parsed=parseFullSentence(raw,q);if(parsed.full){raw=parsed.gap;$('answer').value=raw;$('answer').dataset.extracted='1';flashFixed('secondBefore');flashFixed('secondAfter');}if(!timeout&&!raw){$('micStatus').textContent='Di la respuesta o escríbela antes de comprobar.';$('answer').focus();return}answered=true;clearTimer();stopRecognition();const valid=(q.answers?.length?q.answers:[q.answer]).filter(Boolean),ok=!timeout&&valid.some(x=>canon(x)===canon(raw)),usedVoice=$('answer').dataset.voice==='1';if(ok)session.correct++;if(usedVoice)session.voiceAnswers++;const result={qid:q._qid,n:q.n,first:q.first,keyword:q.keyword,user:raw,expected:q.display||valid[0]||'',correct:ok,timeout,skill:q.skill||'',explanation:q.explanation||'',usedVoice};session.results.push(result);$('answer').disabled=true;$('micBtn').disabled=true;$('checkBtn').disabled=true;$('retryBtn').disabled=true;$('scoreTop').textContent=`${session.correct} ✓`;const f=$('feedback');f.className=`feedback ${ok?'ok':'bad'}`;f.innerHTML=ok?`<b>Correcto.</b><span class="expected">${esc(result.expected)}</span><small>${esc(result.skill)}</small>`:`<b>${timeout?'Tiempo.':'Revisa la transformación.'}</b><span>Respuesta: <span class="expected">${esc(result.expected)}</span></span>${raw?`<small>Has dicho/escrito: ${esc(raw)}</small>`:''}<small>${esc(result.explanation)}</small>`;$('nextBtn').textContent=index===session.questions.length-1?'VER RESULTADO':'SIGUIENTE';$('nextBtn').classList.remove('hidden');}
function next(){if(!answered)return;index++;if(index>=session.questions.length)finishSession();else renderQuestion()}
function finishSession(){clearTimer();stopRecognition();if(!session)return;const data=load(),durationSec=Math.round((Date.now()-session.startedAt)/1000);for(const r of session.results){const h=data.items[r.qid]||{attempts:0,correct:0};h.attempts++;if(r.correct)h.correct++;data.items[r.qid]=h}data.sessions.push({id:Date.now(),completedAt:new Date().toISOString(),correct:session.correct,total:session.questions.length,voiceAnswers:session.voiceAnswers,durationSec,secondsPerQuestion,results:session.results.slice(-SESSION_SIZE)});save(data);const counts=medalCounts();$('resultScore').textContent=`${session.correct}/${session.questions.length}`;$('resultSub').textContent=`${Math.round(session.correct/session.questions.length*100)}% · ${session.voiceAnswers} respuestas por voz · ${secondsPerQuestion===0?'sin límite':('límite '+secondsPerQuestion+'s')}`;$('achievement').innerHTML=window.AdrianAchievements?.badgeHtml?.(session.correct,session.questions.length)||'';$('resultMedals').innerHTML=window.AdrianAchievements?.medalStripHtml?.(counts,{context:'summary',compact:true})||'';$('review').innerHTML=session.results.filter(x=>!x.correct).slice(0,8).map(x=>`<div class="review-row bad"><b>${esc(x.keyword)} · ${esc(x.expected)}</b><small>${esc(x.first)}</small></div>`).join('')||'<div class="review-row"><b>Sesión limpia.</b><small>No hubo errores.</small></div>';window.AdrianAchievements?.play?.(null,session.correct,session.questions.length);show('resultScreen');renderHome();}
function renderStats(){const a=aggregate(),d=load(),counts=medalCounts(),recent=(d.sessions||[]).slice(-8);$('statsSummary').innerHTML=`<div class="stats-card"><b>${a.sessions}</b><span>sesiones completas</span></div><div class="stats-card"><b>${a.accuracy}%</b><span>${a.correct}/${a.total} respuestas correctas</span></div><div class="stats-card"><b>${a.voiceRate}%</b><span>respuestas registradas por voz</span></div><div class="stats-card"><b>${recent.length?Math.round(recent.reduce((n,x)=>n+x.correct/x.total*100,0)/recent.length):0}%</b><span>media de las últimas ${recent.length} sesiones</span></div>`;$('statsMedals').innerHTML=window.AdrianAchievements?.medalStripHtml?.(counts,{context:'summary',compact:false})||'';show('statsScreen')}
function micTest(){if(!SpeechRecognition){$('micTestResult').textContent='Este navegador no ofrece reconocimiento de voz.';return}const box=$('micTestResult'),target={value:''};const r=configureRecognition(target,box,v=>{box.textContent=v?`He entendido: “${v}”`:'No he recibido ninguna frase.'});recognition=r;try{r.start()}catch{}}
function clearAnswer(){$('answer').value='';$('answer').dataset.voice='0';$('micStatus').textContent='Respuesta borrada. Puedes hablar otra vez o escribir.';$('answer').focus()}
$('micBtn').onclick=()=>{if(!answered){$('answer').dataset.voice='1';startMic()}};$('checkBtn').onclick=()=>submitAnswer(false);$('retryBtn').onclick=clearAnswer;$('nextBtn').onclick=next;$('startBtn').onclick=startSession;$('againBtn').onclick=startSession;$('statsBtn').onclick=renderStats;$('statsHomeBtn').onclick=()=>{renderHome();show('startScreen')};$('resultHomeBtn').onclick=()=>{renderHome();show('startScreen')};$('quitBtn').onclick=()=>{clearTimer();stopRecognition();renderHome();show('startScreen')};$('practiceBtn').onclick=()=>show('micScreen');$('micHomeBtn').onclick=()=>{stopRecognition();show('startScreen')};$('micTestBtn').onclick=micTest;function setTime(sec,source=null){secondsPerQuestion=Math.max(0,Number(sec)||0);document.querySelectorAll('.time-choice').forEach(x=>x.classList.toggle('active',x===source));if(source&&$('customTime'))$('customTime').value=''}document.querySelectorAll('.time-choice').forEach(b=>b.onclick=()=>setTime(Number(b.dataset.sec),b));$('customTimeBtn').onclick=()=>{const v=Math.max(15,Math.round(Number($('customTime').value)||180));$('customTime').value=v;setTime(v,null)};$('customTime').addEventListener('keydown',e=>{if(e.key==='Enter')$('customTimeBtn').click()});
$('answer').addEventListener('input',()=>{if(!listening&&document.activeElement===$('answer')){$('answer').dataset.voice='0';$('answer').dataset.extracted='0';clearTimeout(inputDebounce);inputDebounce=setTimeout(extractFullSentenceFromInput,420)}});$('answer').addEventListener('keydown',e=>{if(e.key==='Enter'&&!answered)submitAnswer(false)});
renderHome();show('startScreen');if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
