const APP_VERSION='1.0.1';
window.KEYWORD_SPEAKING_VERSION=APP_VERSION;
const $=id=>document.getElementById(id);
const PAPERS=[...(window.ADAPTIVE_EXAM_CAMBRIDGE_PAPERS||[]),...(window.ADAPTIVE_EXAM_PAPERS||[])];
const QUESTIONS=PAPERS.flatMap(p=>(p.parts?.[4]?.items||[]).map((it,i)=>({...it,_paper:p.label||p.id,_paperId:p.id,_exam:Number(p.examNumber)||null,_qid:(p.id||p.label)+':'+(it.n??i)}))).filter(q=>q.first&&q.keyword&&q.secondBefore!==undefined&&q.secondAfter!==undefined&&(q.answers?.length||q.answer));
const SESSION_SIZE=15,STATS_KEY='keywordSpeakingStatsV1',APP_ID='keyword-speaking';
let secondsPerQuestion=180,session=null,index=0,timerId=null,deadline=0,recognition=null,listening=false,answered=false,lastVoiceTranscript='',composing=false,gboardIdleTimer=null;
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function norm(v){return String(v||'').toLowerCase().replace(/[’‘]/g,"'").replace(/[.,!?;:]/g,' ').replace(/\s+/g,' ').trim();}
function canon(v){let s=norm(v);s=s.replace(/\b(i|you|we|they|he|she|it)'d\s+(\w+)/g,(_,who,verb)=>who+' '+(/^(spent|been|done|gone|seen|taken|given|made|known|left|lost|found|bought|thought|said|written|read|heard|met|paid|had|kept)$/.test(verb)?'had':'would')+' '+verb);const map=[["won't","will not"],["can't","cannot"],["shan't","shall not"],["don't","do not"],["doesn't","does not"],["didn't","did not"],["isn't","is not"],["aren't","are not"],["wasn't","was not"],["weren't","were not"],["haven't","have not"],["hasn't","has not"],["hadn't","had not"],["wouldn't","would not"],["shouldn't","should not"],["couldn't","could not"],["mustn't","must not"],["i'm","i am"],["you're","you are"],["we're","we are"],["they're","they are"],["he's","he is"],["she's","she is"],["it's","it is"]];for(const [a,b] of map)s=s.split(a).join(b);return s.replace(/\s+/g,' ').trim();}
function speechCanon(v){let s=canon(v);const map=[["i'd","i would"],["you'd","you would"],["we'd","we would"],["they'd","they would"],["he'd","he would"],["she'd","she would"],["i'll","i will"],["you'll","you will"],["we'll","we will"],["they'll","they will"],["he'll","he will"],["she'll","she will"]];for(const [a,b] of map)s=s.split(a).join(b);return s;}
function expectedVariants(q){
 const raw=[...(q.answers||[]),q.answer,q.display].filter(Boolean),out=[];
 function expand(s){const m=s.match(/\(([^)]+)\)/);if(!m){out.push(s.replace(/\s+/g,' ').trim());return;}
 expand(s.slice(0,m.index)+s.slice(m.index+m[0].length));expand(s.slice(0,m.index)+m[1]+s.slice(m.index+m[0].length));}
 for(const item of raw)for(const alt of String(item).split(/\s+\/\s+/))expand(alt);
 return [...new Set(out.filter(Boolean))];
}
function wordCountCambridge(v){return speechCanon(v).split(' ').filter(Boolean).length;}
function containsKeyword(v,q){const u=speechCanon(v).split(' '),k=speechCanon(q.keyword||'').split(' ');return k.every(w=>u.includes(w));}
function longestCommonRun(a,b){const A=speechCanon(a).split(' ').filter(Boolean),B=speechCanon(b).split(' ').filter(Boolean);let best=0;for(let i=0;i<A.length;i++)for(let j=0;j<B.length;j++){let n=0;while(i+n<A.length&&j+n<B.length&&A[i+n]===B[j+n])n++;if(n>best)best=n;}return best;}
function scoreTransformation(user,q){const raw=String(user||'').trim(),variants=expectedVariants(q);if(!raw)return{points:0,max:2,exact:false,variant:variants[0]||'',reason:'empty'};const wc=wordCountCambridge(raw);for(const v of variants)if(canon(raw)===canon(v))return{points:2,max:2,exact:true,variant:v,reason:'exact'};if(wc<2||wc>5||!containsKeyword(raw,q))return{points:0,max:2,exact:false,variant:variants[0]||'',reason:wc<2||wc>5?'word-count':'keyword'};let best={run:0,variant:variants[0]||''};for(const v of variants){const run=longestCommonRun(raw,v),need=Math.max(2,Math.ceil(wordCountCambridge(v)/2));if(run>best.run)best={run,variant:v,need};if(run>=need)return{points:1,max:2,exact:false,variant:v,reason:'partial'};}return{points:0,max:2,exact:false,variant:best.variant,reason:'mismatch'};}
function parseFullSentence(text,q=current()){
 if(!q)return {full:false,gap:String(text||'')};
 const t=norm(text).split(' ').filter(Boolean),b=norm(q.secondBefore).split(' ').filter(Boolean),a=norm(q.secondAfter).split(' ').filter(Boolean);
 const pre=b.every((v,i)=>t[i]===v),suf=a.every((v,i)=>t[t.length-a.length+i]===v);
 const full=(b.length+a.length)>0&&pre&&suf&&t.length>b.length+a.length;
 return {full,gap:full?t.slice(b.length,t.length-a.length||undefined).join(' '):String(text||''),preScore:pre?1:0,sufScore:suf?1:0};
}
function flashFixed(id){const el=$(id);if(!el)return;el.classList.remove('heard');void el.offsetWidth;el.classList.add('heard');clearTimeout(el._heardTimer);el._heardTimer=setTimeout(()=>el.classList.remove('heard'),760);}
function showRecognitionProgress(text,commit=false){const p=parseFullSentence(text);if(p.preScore>=.58)flashFixed('secondBefore');if(p.sufScore>=.58)flashFixed('secondAfter');if(p.full){if(commit||listening){$('answer').value=p.gap;$('answer').dataset.extracted='1';}$('micStatus').textContent=`Frase completa reconocida · hueco: “${p.gap}”`;return p;}if(commit){$('answer').value=text.trim();$('answer').dataset.extracted='0';}return p;}
function show(id){['startScreen','gameScreen','resultScreen','statsScreen','micScreen'].forEach(x=>$(x).classList.toggle('hidden',x!==id));window.scrollTo(0,0);}
function load(){try{return JSON.parse(localStorage.getItem(STATS_KEY))||{sessions:[],items:{}}}catch{return{sessions:[],items:{}}}}
function save(x){localStorage.setItem(STATS_KEY,JSON.stringify(x));}
function medalCounts(){return window.AdrianAchievements?.countsFromHistory?.(load().sessions)||{blue:0,violet:0,gold:0};}
function aggregate(){const d=load(),s=d.sessions||[],correct=s.reduce((n,x)=>n+(x.correct||0),0),total=s.reduce((n,x)=>n+(x.total||0),0),voice=s.reduce((n,x)=>n+(x.voiceAnswers||0),0),answers=s.reduce((n,x)=>n+(x.questionCount||x.total||0),0);return{sessions:s.length,correct,total,accuracy:total?Math.round(correct/total*100):0,voiceRate:answers?Math.round(voice/answers*100):0};}
function renderHome(){const a=aggregate();$('homeStats').innerHTML=stat(a.sessions,'SESIONES')+stat(a.total?a.accuracy+'%':'—','ACIERTO')+stat(QUESTIONS.length,'PREGUNTAS');$('homeMedals').innerHTML=window.AdrianAchievements?.medalStripHtml?.(medalCounts(),{context:'summary',compact:true})||'';$('speechSupport').textContent=SpeechRecognition?'Micrófono disponible en este navegador.':'Este navegador no ofrece reconocimiento de voz; el teclado seguirá funcionando.';$('speechSupport').classList.toggle('bad',!SpeechRecognition);}
function stat(v,l){return `<div class="stat"><b>${esc(v)}</b><span>${esc(l)}</span></div>`}
function itemHistory(q){return load().items?.[q._qid]||{attempts:0,correct:0,points:0}}
function pickQuestions(){const ranked=QUESTIONS.map(q=>{const h=itemHistory(q),earned=Number.isFinite(h.points)?h.points:(h.correct||0)*2,acc=h.attempts?earned/(h.attempts*2):.45,weight=1.2+(1-acc)*2+1/Math.sqrt(h.attempts+1);return{q,key:Math.random()**(1/weight)}}).sort((a,b)=>b.key-a.key);return ranked.slice(0,Math.min(SESSION_SIZE,ranked.length)).map(x=>x.q)}
function startSession(){stopRecognition();clearTimer();session={startedAt:Date.now(),questions:pickQuestions(),results:[],correct:0,voiceAnswers:0,streak:0};index=0;show('gameScreen');renderQuestion();}
function current(){return session?.questions?.[index]||null}
function renderQuestion(){clearTimer();stopRecognition();answered=false;const q=current();if(!q)return finishSession();$('progressMain').textContent=`${index+1} / ${session.questions.length}`;$('paperLabel').textContent=q._exam?`EXAM ${String(q._exam).padStart(2,'0')}`:String(q._paper||'PART 4').toUpperCase();$('scoreTop').textContent=`${session.correct}/${session.questions.length*2}`;$('questionNo').textContent=`QUESTION ${q.n??index+1}`;$('first').textContent=q.first||'';$('keyword').textContent=q.keyword||'';$('secondBefore').textContent=q.secondBefore||'';$('secondAfter').textContent=q.secondAfter||'';$('answer').value='';$('answer').dataset.extracted='0';lastVoiceTranscript='';composing=false;$('answer').dataset.voice='0';$('answer').disabled=false;$('micBtn').disabled=false;$('checkBtn').disabled=false;$('retryBtn').disabled=false;$('feedback').className='feedback hidden';$('feedback').innerHTML='';$('nextBtn').classList.add('hidden');$('micStatus').textContent=SpeechRecognition?'Di la frase completa o solo el hueco. También puedes dictar con Gboard.':'Escribe el hueco o la frase completa.';resizeAnswer();startTimer();}
function startTimer(){if(secondsPerQuestion===0){$("timerText").textContent="∞";$("timer").style.setProperty("--p",100);$("timer").classList.remove("low");return}deadline=Date.now()+secondsPerQuestion*1000;tick();timerId=setInterval(tick,200)}
function tick(){const left=Math.max(0,Math.ceil((deadline-Date.now())/1000)),p=Math.max(0,Math.min(100,(deadline-Date.now())/(secondsPerQuestion*10)));$('timerText').textContent=left;$('timer').style.setProperty('--p',p);$('timer').classList.toggle('low',left<=15);if(left<=0&&!answered){clearTimer();submitAnswer(true)}}
function clearTimer(){if(timerId){clearInterval(timerId);timerId=null}}
function configureRecognition(target,statusEl,onDone){if(!SpeechRecognition)return null;const r=new SpeechRecognition();r.lang='en-GB';r.continuous=false;r.interimResults=true;r.maxAlternatives=5;r.onstart=()=>{listening=true;statusEl?.classList.add('listening');if(statusEl)statusEl.textContent='Escuchando…';$('micBtn')?.classList.add('listening')};r.onresult=e=>{if(target.id==='answer'&&(answered||recognition!==r))return;let text='';for(let i=0;i<e.results.length;i++)text+=e.results[i][0].transcript+' ';text=text.trim();lastVoiceTranscript=text;if(target.id==='answer'){const p=showRecognitionProgress(text,false);if(!p.full)target.value=text;}else target.value=text;resizeAnswer();};r.onerror=e=>{if(statusEl){statusEl.textContent=e.error==='not-allowed'?'Permiso de micrófono bloqueado. Puedes usar el teclado.':'No he podido reconocerlo. Repite o usa el teclado.';statusEl.classList.remove('listening')}};r.onend=()=>{if(target.id==='answer'&&(answered||recognition!==r))return;listening=false;$('micBtn')?.classList.remove('listening');statusEl?.classList.remove('listening');if(target.id==='answer'&&lastVoiceTranscript){const p=showRecognitionProgress(lastVoiceTranscript,true);if(!p.full&&statusEl)statusEl.textContent=`He entendido: “${target.value.trim()}”. Puedes decir el hueco o la frase completa.`;}else if(statusEl&&target.value.trim())statusEl.textContent=`He entendido: “${target.value.trim()}”.`;onDone?.(target.value.trim())};return r}
function startMic(){if(answered)return;if(!SpeechRecognition){$('answer').focus();return}if(listening){stopRecognition();return}recognition=configureRecognition($('answer'),$('micStatus'),()=>{});try{recognition.start()}catch{}}
function stopRecognition(){if(recognition){try{recognition.stop()}catch{}recognition=null}listening=false;$('micBtn')?.classList.remove('listening')}
function submitAnswer(timeout=false){if(answered||(!timeout&&composing))return;const q=current();let raw=$('answer').value.trim();const parsed=parseFullSentence(raw,q);if(parsed.full){raw=parsed.gap;$('answer').value=raw;$('answer').dataset.extracted='1';flashFixed('secondBefore');flashFixed('secondAfter');}if(!timeout&&!raw){$('micStatus').textContent='Di la respuesta o escríbela antes de comprobar.';$('answer').focus();return}answered=true;clearTimer();stopRecognition();const score=timeout?{points:0,max:2,exact:false,variant:expectedVariants(q)[0]||'',reason:'timeout'}:scoreTransformation(raw,q);session.correct+=score.points;session.streak=score.points===2?(session.streak||0)+1:0;const usedVoice=$('answer').dataset.voice==='1';if(usedVoice)session.voiceAnswers++;resizeAnswer();$('answer').blur();const result={qid:q._qid,n:q.n,first:q.first,keyword:q.keyword,user:raw,expected:score.variant||expectedVariants(q)[0]||'',points:score.points,maxPoints:2,correct:score.points===2,timeout,skill:q.skill||'',explanation:q.explanation||'',usedVoice};session.results.push(result);$('answer').disabled=true;$('micBtn').disabled=true;$('checkBtn').disabled=true;$('retryBtn').disabled=true;$('scoreTop').textContent=`${session.correct}/${session.questions.length*2}`;const f=$('feedback');f.className=`feedback ${score.points===2?'ok':score.points===1?'partial':'bad'}`;if(score.points===2)f.innerHTML=`<b>2/2 · Correcto.</b><span class="expected">${esc(result.expected)}</span><small>${esc(result.skill)}</small>`;else if(score.points===1)f.innerHTML=`<b>1/2 · Parcial estimado.</b><span>Una parte importante coincide con la estructura correcta.</span><small>Solución completa: <span class="expected">${esc(result.expected)}</span></small>`;else f.innerHTML=`<b>${timeout?'Tiempo.':'0/2 · Revisa la transformación.'}</b><span>Respuesta: <span class="expected">${esc(result.expected)}</span></span>${raw?`<small>Has dicho/escrito: ${esc(raw)}</small>`:''}<small>${esc(result.explanation)}</small>`;f.innerHTML+='<small>+'+score.points+' puntos · '+session.correct+'/'+session.questions.length*2+(session.streak>1?' · Racha de '+session.streak:'')+'</small>';$('nextBtn').textContent=index===session.questions.length-1?'VER RESULTADO':'SIGUIENTE';$('nextBtn').classList.remove('hidden');}
function next(){if(!answered)return;index++;if(index>=session.questions.length)finishSession();else renderQuestion()}
function finishSession(){clearTimer();stopRecognition();if(!session)return;const data=load(),durationSec=Math.round((Date.now()-session.startedAt)/1000),sessionId='kw-'+(crypto.randomUUID?.()||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2));for(const r of session.results){const h=data.items[r.qid]||{attempts:0,correct:0,points:0};h.attempts++;h.points=(h.points||0)+(r.points||0);if(r.points===2)h.correct=(h.correct||0)+1;data.items[r.qid]=h}const savedSession={id:sessionId,eventId:sessionId,completedAt:new Date().toISOString(),correct:session.correct,total:session.questions.length*2,questionCount:session.questions.length,voiceAnswers:session.voiceAnswers,durationSec,secondsPerQuestion,results:session.results.slice(-SESSION_SIZE)};data.sessions.push(savedSession);save(data);const counts=medalCounts();$('resultScore').textContent=`${session.correct}/${session.questions.length*2}`;$('resultSub').textContent=`${Math.round(session.correct/(session.questions.length*2)*100)}% · ${session.voiceAnswers} respuestas por voz · ${secondsPerQuestion===0?'sin límite':('límite '+secondsPerQuestion+'s')}`;$('achievement').innerHTML=window.AdrianAchievements?.badgeHtml?.(session.correct,session.questions.length*2)||'';$('resultMedals').innerHTML=window.AdrianAchievements?.medalStripHtml?.(counts,{context:'summary',compact:true})||'';const misses=session.results.filter(x=>(x.points||0)<2);$('review').innerHTML=misses.map(x=>`<div class="review-row ${x.points===1?'partial':'bad'}"><b>${x.points||0}/2 · ${esc(x.keyword)}</b><small><strong>Tu respuesta:</strong> ${esc(x.user||'—')}</small><small><strong>Solución:</strong> ${esc(x.expected)}</small><small>${esc(x.first)}</small>${x.explanation?`<small>${esc(x.explanation)}</small>`:''}</div>`).join('')||'<div class="review-row"><b>Sesión limpia.</b><small>30/30 · todas las transformaciones correctas.</small></div>';window.AdrianAchievements?.play?.(null,session.correct,session.questions.length*2);show('resultScreen');renderHome();Promise.resolve(window.AdrianOca?.resolve?.({eventId:'keyword:'+sessionId,appId:APP_ID,correct:session.correct,total:session.questions.length*2})).catch(()=>{});}
function renderStats(){const a=aggregate(),d=load(),counts=medalCounts(),recent=(d.sessions||[]).slice(-8);$('statsSummary').innerHTML=`<div class="stats-card"><b>${a.sessions}</b><span>sesiones completas</span></div><div class="stats-card"><b>${a.accuracy}%</b><span>${a.correct}/${a.total} puntos acumulados</span></div><div class="stats-card"><b>${a.voiceRate}%</b><span>respuestas registradas por voz</span></div><div class="stats-card"><b>${recent.length?Math.round(recent.reduce((n,x)=>n+x.correct/x.total*100,0)/recent.length):0}%</b><span>media de las últimas ${recent.length} sesiones</span></div>`;$('statsMedals').innerHTML=window.AdrianAchievements?.medalStripHtml?.(counts,{context:'summary',compact:false})||'';show('statsScreen')}
function micTest(){if(!SpeechRecognition){$('micTestResult').textContent='Este navegador no ofrece reconocimiento de voz.';return}const box=$('micTestResult'),target={value:''};const r=configureRecognition(target,box,v=>{box.textContent=v?`He entendido: “${v}”`:'No he recibido ninguna frase.'});recognition=r;try{r.start()}catch{}}
function clearAnswer(){stopRecognition();lastVoiceTranscript='';$('answer').value='';resizeAnswer();$('answer').dataset.voice='0';$('micStatus').textContent='Respuesta borrada. Puedes hablar otra vez o escribir.';$('answer').focus()}
$('micBtn').onclick=()=>{if(!answered){$('answer').dataset.voice='1';startMic()}};$('checkBtn').onclick=()=>submitAnswer(false);$('retryBtn').onclick=clearAnswer;$('nextBtn').onclick=next;$('startBtn').onclick=startSession;$('againBtn').onclick=startSession;$('statsBtn').onclick=renderStats;$('statsHomeBtn').onclick=()=>{renderHome();show('startScreen')};$('resultHomeBtn').onclick=()=>{renderHome();show('startScreen')};$('quitBtn').onclick=()=>{clearTimer();stopRecognition();renderHome();show('startScreen')};$('practiceBtn').onclick=()=>show('micScreen');$('micHomeBtn').onclick=()=>{stopRecognition();show('startScreen')};$('micTestBtn').onclick=micTest;function setTime(sec,source=null){secondsPerQuestion=Math.max(0,Number(sec)||0);document.querySelectorAll('.time-choice').forEach(x=>x.classList.toggle('active',x===source));if(source&&$('customTime'))$('customTime').value=''}document.querySelectorAll('.time-choice').forEach(b=>b.onclick=()=>setTime(Number(b.dataset.sec),b));$('customTimeBtn').onclick=()=>{const v=Math.max(15,Math.round(Number($('customTime').value)||180));$('customTime').value=v;setTime(v,null)};$('customTime').addEventListener('keydown',e=>{if(e.key==='Enter')$('customTimeBtn').click()});
$('answer').addEventListener('compositionstart',()=>{composing=true;clearTimeout(gboardIdleTimer)});$('answer').addEventListener('compositionupdate',()=>{clearTimeout(gboardIdleTimer)});$('answer').addEventListener('compositionend',()=>{composing=false;resizeAnswer()});$('answer').addEventListener('input',e=>{resizeAnswer();if(!listening&&document.activeElement===$('answer')){$('answer').dataset.voice='0';$('answer').dataset.extracted='0'}});$('answer').addEventListener('blur',()=>{clearTimeout(gboardIdleTimer)});$('answer').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&!composing&&!answered){e.preventDefault();submitAnswer(false)}});
renderHome();show('startScreen');

function resizeAnswer(){const e=$('answer');if(!e)return;e.style.height='auto';e.style.height=Math.max(72,e.scrollHeight+4)+'px';}
$('answer').addEventListener('focus',()=>{resizeAnswer();setTimeout(()=>{if(document.activeElement===$('answer'))$('answer').scrollIntoView({block:'center',behavior:'smooth'})},250)});
window.visualViewport?.addEventListener('resize',()=>{if(document.activeElement===$('answer')){resizeAnswer();$('answer').scrollIntoView({block:'center'})}});
window.addEventListener('resize',resizeAnswer);
